/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases_y_ventanas;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author ESTUDIANTE
 */
public class InicioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InicioPrincipal
     */
    public InicioPrincipal() {
        initComponents();
        
         String query = "Select NombresUsuario, ApellidosUsuario From tbUsuarios Where UsuarioUsuario = ?";
        
        VentanaInicioSesion inicioSesion = new VentanaInicioSesion();
        String usuario = inicioSesion.user;
        
        try {
            PreparedStatement nombre = ConexionSQL.getConnection().prepareStatement(query);
            nombre.setString(1, usuario);            
            ResultSet resultSet = nombre.executeQuery();
                    
           if (resultSet.next()) 
            {
                String nombreUs = resultSet.getString("NombresUsuario");
                String apellidoUs = resultSet.getString("ApellidosUsuario"); 
                
                lblSaludo.setText("Bienvenid@ " + nombreUs + " " + apellidoUs);
            } 
           else 
           {
                System.out.println("a");
            }

        } catch (Exception e) {
            System.out.println("ERROR en el query: " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSaludo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaludo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSaludo.setForeground(new java.awt.Color(0, 0, 0));
        lblSaludo.setText("Saludo");
        jPanel2.add(lblSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 640, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSaludo;
    // End of variables declaration//GEN-END:variables
}
